### ISSUE TITLE
Document RSSI Calculation

### ISSUE THREAD

**Issue by trademark18** [reelyactive/barnowl#4]
I've recently migrated to v1.0.0 from the previous versions of Barnowl.  I noticed that RSSI now comes as dBm instead of whatever it was before (usually something in the range of ~150 to ~220).  This caused a few things to break

Perhaps I've missed it, but where can I go to understand how the old values were calculated and how it relates to the new dBm values?  I tried digging through the repo and found [this](https://github.com/reelyactive/barnowl/blob/90fcb03f386d94d3ad5c1a0338d9e987251cea08/lib/core/listenerservice/hcilistener.js#L129), but I'm not sure if this really tells the whole story.

```javascript
reelData += ('0' + (rssi + 128).toString(16)).substr(-2); // RSSI
```

I'm not using reels, and I'm using a Raspberry Pi with the BarnowHci package.

Thanks!

**Comment by jeffyactive** [comment]
Hi @trademark18, you're right that barnowl@1.x has adopted dBm values for consistency across platforms while barnowl@0.x used values that were always positive integers.  In both cases, each unit represents 1 dBm, however, in the case of barnowl@0.x, there was effectively an offset applied to the real dBm value such that outputs were in the range of ~150 to ~220 for HCI on the Pi.

The easiest workaround to continue using your previous code would be to add a constant value (ex: 250) to the barnowl@1.x RSSI values such that they approach what your code expects.  For example -80 dBm + 250 = 170.

If you want to track down the exact number, like you pointed out, the previous HCI code adjusted the true RSSI as follows: https://github.com/reelyactive/barnowl/blob/release-0.4/lib/core/listenerservice/hcilistener.js#L129

which was then interpreted using this function: https://github.com/reelyactive/barnowl/blob/release-0.4/lib/decoders/reelpacketdecoder.js#L33

Hope that helps!  Kindly close the issue if so, and don't hesitate to share any offset that you settle on.

**Comment by trademark18** [comment]
@jeffyactive Thanks for the clear explanation.  Since it's still a "higher is better" number, I just adjusted my thresholds and it seems to be fine.  Perhaps there's a blog post or a release notes document that I'm not aware of, but it would be helpful to see something like that either in the Readme or on the website somewhere.  Just so people porting to 1.x can know what the critical changes are.  Anyway your answer has cleared up this issue for me, so I'll close the issue.  Thanks again!
